### ISSUE TITLE
Inner struct validation not working

### ISSUE THREAD

**Issue by igventurelli** [golodash/galidator#1]
**Describe the bug**
First of all, this package is really cool :)
It works for "single level" structs, but not for inner structs.

**To Reproduce**
Create a struct with a inner one, for example:

    type Organization struct {
	    Id      primitive.ObjectID `bson:"_id,omitempty,omitempty" json:"id"`
	    Plan    *Plan                    `bson:"plan,omitempty" json:"plan" g:"required" required:"Organization plan is required"`
    }
    
    type Plan struct {
	    Id          string      `bson:"id,omitempty" json:"id" g:"required" required:"Plan id is required"`
    }

And validate it:

    func validate(org *model.Organization) []string {
	    errors := []string{}
    
	    validator := g.Validator(model.Organization{})
	    validationErrors := validator.Validate(org)
    
	    if validationErrors != nil {
		    errorsMap, ok := validationErrors.(map[string]interface{})
		    if !ok {
			    log.Fatalf("Error while trying to validated payload: %s", errors)
		    }
		    for _, value := range errorsMap {
			    attributeErrors, ok := value.([]string)
			    if !ok {
				    log.Fatalf("Error while trying to validated payload: %s", attributeErrors)
			    }
			    errors = append(errors, attributeErrors...)
		    }
	    }
	    return errors
    }

**Expected behavior**
It's expected that the validator do validate all levels of the structure and apply the rules set on the nested structs (in this case, `Plan`)

**Screenshots**
N/A

**Environment:**
 - Go version: 1.19.2
 - Operation System: macOS Ventura 13.0
 - GoTestcontainers: 0.15.0

**Additional context**
I'm new in Go, so maybe I'm doing something wrong. But if it's really a bug, I may try to fix it in a PR, if it's welcome  
Also, is there a better way to get all the error messages as a array/slice of strings?

**Comment by maktoobgar** [comment]
Thanks for opening the first issue of the repository. 😁
I think I already know where this problem is coming from. (You defined *Plan in Organization struct and that's preventing galidator from generating validator right)
Let me see if I can fix it so that pointers don't cause problems.
And of course you can contribute if you are interested in this repository.
I will be happy.

**Comment by maktoobgar** [comment]
Fixed the problem in [v0.0.2](https://github.com/golodash/galidator/releases/tag/v0.0.2), have a look.
If there was any other problem, Inform me and I'll be happy to fix it. 🙌

**Comment by igventurelli** [comment]
Wow! That was fast! Thanks, I'll try soon!
